Added new parameter ItemGUID
eway-crm/XsltTransformations pull request #1
Opened 2024-09-09 11:28 UTC by AdamDrobny

Added new parameter ItemGUID so word template could be created with chosen GUID from default eWay DB.

2024-09-20 08:51 UTC, rstefko requested changes

2024-09-20 08:51 UTC, rstefko commented on WordprocessingML/Wml2Ew/Program.cs
> +            if (itemGuid != null && isValid != true)
Tady by bylo lepší to volat takto, ať zbytečně nevoláš TryParse s null hodnotou:

`
if (itemGuid != null && !Guid.TryParseExact(itemGuid, "D", out _))
`

2024-09-20 08:51 UTC, rstefko commented on WordprocessingML/Wml2Ew/Program.cs
> +                .Replace(Constants.ITEMGUID_PARAMETER, itemGuid)
Tady viz. komentář níže musí teda být: `itemGuid == null ? "NULL" : $"'{itemGuid}'"`

2024-09-20 08:51 UTC, rstefko commented on WordprocessingML/Wml2Ew/XsltTransformation.sql
> +	SET @DefaultItemGUID = N'$ItemGUID$'; --Fill ItemGUID from default eWay DB when manually deploying system word template on the server for the first time
Parametr bych spíše nazval @ItemGUID `SET @ItemGUID = $ItemGUID$`. Výchozí hodnota by měla být NULL a vkládat tam bude jen pokud přijde paramtrem.

Komentář by měl spíš být `-- Fill GUID if you need to use the same identifier across multiple databases`

2024-09-20 08:51 UTC, rstefko commented on WordprocessingML/Wml2Ew/XsltTransformation.sql
> +	SET @XsltGUID = IIF(@DefaultItemGUID <> '', @DefaultItemGUID, NEWID());
Tady pak dát ISNULL.

2024-09-24 10:44 UTC, AdamDrobny commented
Upraveno

2024-10-01 13:03 UTC, merged